from .yolo_tracker import NODE_CLASS_MAPPINGS as NODES, NODE_DISPLAY_NAME_MAPPINGS as DISPLAY_NAMES

NODE_CLASS_MAPPINGS = {
    **NODES,
}
NODE_DISPLAY_NAME_MAPPINGS = {
    **DISPLAY_NAMES,
}
__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
